# Generated by Django 5.2.7 on 2025-11-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alignedparty',
            name='image',
        ),
    ]
