# Generated by Django 5.2.7 on 2025-11-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll_app', '0002_remove_alignedparty_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='aligned_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='poll_app.alignedparty'),
        ),
    ]
